import type { Metadata } from "next";
import Script from 'next/script';
import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const tgScript = "https://telegram.org/js/telegram-web-app.js";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
      {/* eslint-disable-next-line @next/next/no-sync-scripts */}
      <script src={tgScript} />
    </Head>
    <body className={inter.className}>{children}</body>
    {/*<Script*/}
    {/*  src={tgScript}*/}
    {/*  strategy="beforeInteractive"*/}
    {/*/>*/}
    </html>
  );
}
